server:
  port: 8082
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource #数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/consume?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#    formcontent:
#      filter:
#        enabled: true


#日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
